In [5]:
import pandas as pd
df = pd.read_csv('시청자미디어재단_체험형미디어교육_20221109.csv', encoding='cp949')

In [6]:
df

,센터명,강좌명,강사명,교육시작일자,교육종료일자,강좌내용,교육대상구분,교육방법구분,운영요일,강좌정원수,데이터기준일자
0,서울시청자미디어센터,상설미디어체험 교육,"이수현,김민호",2022-11-12,2022-11-26,상설미디어체험(뉴스앵커체험 등),일반,오프라인,토,25,2022-11-09
1,서울시청자미디어센터,찾아가는미디어나눔버스 체험 교육,"김도경,이수현",2022-11-21,2022-11-21,찾아가는미디어나눔버스 체험,청소년,오프라인,월,25,2022-11-09
2,서울시청자미디어센터,찾아가는미디어나눔버스 체험,"김도경,이수현",2022-11-22,2022-11-22,찾아가는미디어나눔버스 체험,청소년,오프라인,화,25,2022-11-09
3,서울시청자미디어센터,찾아가는미디어나눔버스 체험,"김도경,이수현",2022-11-23,2022-11-23,찾아가는미디어나눔버스 체험,청소년,오프라인,수,25,2022-11-09
4,서울시청자미디어센터,찾아가는미디어나눔버스 체험,"김도경,이수현",2022-11-25,2022-11-25,찾아가는미디어나눔버스 체험,청소년,오프라인,금,25,2022-11-09
...,...,...,...,...,...,...,...,...,...,...,...
94,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"류은애,김은자",2022-11-30,2022-11-30,TV 뉴스 제작 및 영상합성 크로마키 체험,중학생,오프라인,수,25,2022-11-09
95,충북시청자미디어센터,TV체험(뉴스체험),미정,2022-11-01,2022-11-30,"아나운서, 기자, 기상캐스터 등 역할을 나누어 뉴스 제작 과정을 체험해보는 프로그램",초등학생 이상,오프라인,"월,화,수,목,금,토",15,2022-11-09
96,충북시청자미디어센터,라디오체험(DJ체험),미정,2022-11-01,2022-11-30,"라디오 프로그램을 작가, DJ, 게스트가 되어 라디오 프로그램을 제작해보는 체험",초등학생 이상,오프라인,"월,화,수,목,금,토",15,2022-11-09
97,충북시청자미디어센터,유아 크로마키 체험,미정,2022-11-01,2022-11-30,유아 대상 크로마키를 통해 다양한 놀이를 해보는 체험,6~7세,오프라인,"월,화,수,목,금,토",15,2022-11-09
98,충북시청자미디어센터,AI 체험,미정,2022-11-01,2022-11-30,인공지능에 대해 이해하고 머신러닝을 여러 방법으로 알아보는 체험,초등학생 이상,오프라인,"월,화,수,목,금,토",15,2022-11-09

In [7]:
df['센터명'].unique()#어느센터에서

array(['서울시청자미디어센터', '울산시청자미디어센터', '강원시청자미디어센터', '대전시청자미디어센터',
       '광주시청자미디어센터', '부산시청자미디어센터', '인천시청자미디어센터', '충북시청자미디어센터'],
      dtype=object)

In [8]:
df['강좌명'].unique()#어떤강좌를

array(['상설미디어체험 교육', '찾아가는미디어나눔버스 체험 교육', '찾아가는미디어나눔버스 체험', '미디어 체험 교육',
       '생방송톡톡TV', 'DJ수다박스', '초록세상마법학교', '오늘은NEWS데이', '찰칵애니',
       '미고의 미디어 탐방기', '우리반데이터만들기', '알듯말듯 알고리즘 알려줄게 알고리즘', '무지개TV',
       '꼼지락뉴스', '폴리체험', 'VR체험', '나눔버스_천안시청 교육청소년과', '센터_대전광역시노인복지관',
       '센터_청소년정책연구원', '미디어체험', '온라인미디어체험(ZOOM)', '드림러너', '상설미디어체험',
       '라디오체험', 'TV뉴스체험', '스톱모션 제작 체험', '크로마키체험', '찾아가는 미디어나눔버스(TV뉴스체험)',
       'TV체험(뉴스체험)', '라디오체험(DJ체험)', '유아 크로마키 체험', 'AI 체험'], dtype=object)

In [9]:
df['강사명'].unique()#누가

array(['이수현,김민호', '김도경,이수현', '전윤겸', '정혜영', '박민주', '김은희', '장미경', '김현주',
       '도현아', '곽은민', '김윤아', '손영주,윤기숙,정선애,이나미', '윤기숙,정선애', '장정우,최영은',
       '김선희외2', '김수현외1', '김은수외3', '미정', '김은미', '백진영,이희주', '류은애,김은자',
       '백진영,김은자', '이두인,이희주', '박희영,이성희'], dtype=object)

In [11]:
df['교육종료일자'-'교육시작일자'].unique()#얼마나

array(['2022-11-12', '2022-11-21', '2022-11-22', '2022-11-23',
       '2022-11-25', '2022-11-07', '2022-11-08', '2022-11-09',
       '2022-11-10', '2022-11-11', '2022-11-14', '2022-11-17',
       '2022-11-18', '2022-11-24', '2022-11-01', '2022-11-16',
       '2022-11-26', '2022-11-02', '2022-11-03', '2022-11-04',
       '2022-11-05', '2022-11-15', '2022-11-19', '2022-11-28',
       '2022-11-29', '2022-11-30'], dtype=object)

In [12]:
df['교육대상구분'].unique()#누구한테

array(['일반', '청소년', '유아', '초등학생', '미취학', '중학생', '유아,아동', '초등학생 이상',
       '중고등학생', '노인(65세~)', '모든연령', '고등학생', '지역주민', '고등학생,장애인', '성인',
       '대학생', '성인,장애인', '중학생,장애인', '6~7세'], dtype=object)

In [18]:
df['센터명'].value_counts()rename_axis('unique_values').reset_index(name='counts')

  unique_values  counts
0    인천시청자미디어센터      28
1    부산시청자미디어센터      26
2    울산시청자미디어센터      24
3    서울시청자미디어센터       6
4    강원시청자미디어센터       4
5    대전시청자미디어센터       4
6    충북시청자미디어센터       4
7    광주시청자미디어센터       3

In [19]:
df['교육대상구분'].value_counts().rename_axis('unique_values').reset_index(name='counts')

   unique_values  counts
0           초등학생      28
1           지역주민      26
2            미취학       7
3            중학생       6
4        초등학생 이상       6
5            청소년       4
6           고등학생       3
7       고등학생,장애인       3
8       노인(65세~)       2
9            대학생       2
10         중고등학생       2
11          모든연령       2
12            성인       2
13       중학생,장애인       1
14        성인,장애인       1
15            일반       1
16         유아,아동       1
17            유아       1
18          6~7세       1

In [20]:
df['교육방법구분'].value_counts().rename_axis('unique_values').reset_index(name='counts')

  unique_values  counts
0          오프라인      97
1           온라인       2

In [21]:
df['운영요일'].value_counts().rename_axis('unique_values').reset_index(name='counts')

  unique_values  counts
0             금      19
1             수      18
2             화      15
3             목      15
4             월      11
5   월,화,수,목,금,토      11
6             토      10

In [23]:
df['강좌정원수'].value_counts().rename_axis('unique_values').reset_index(name='counts')

    unique_values  counts
0              20      34
1              25      32
2              15       8
3              23       8
4              10       4
5              12       3
6              14       2
7              28       2
8              50       1
9              40       1
10              8       1
11              4       1
12             21       1
13             17       1

In [33]:
df['강좌명']=df['강좌명'].apply(lambda x: '찾아가는미디어나눔버스 체험' if '찾아가는미디어나눔버스 체험' in x else x)

In [30]:
df

,센터명,강좌명,강사명,교육시작일자,교육종료일자,강좌내용,교육대상구분,교육방법구분,운영요일,강좌정원수,데이터기준일자
0,서울시청자미디어센터,상설미디어체험 교육,"이수현,김민호",2022-11-12,2022-11-26,상설미디어체험(뉴스앵커체험 등),일반,오프라인,토,25,2022-11-09
1,서울시청자미디어센터,찾아가는미디어나눔버스 체험 교육,"김도경,이수현",2022-11-21,2022-11-21,찾아가는미디어나눔버스 체험,청소년,오프라인,월,25,2022-11-09
2,서울시청자미디어센터,찾아가는미디어나눔버스 체험,"김도경,이수현",2022-11-22,2022-11-22,찾아가는미디어나눔버스 체험,청소년,오프라인,화,25,2022-11-09
3,서울시청자미디어센터,찾아가는미디어나눔버스 체험,"김도경,이수현",2022-11-23,2022-11-23,찾아가는미디어나눔버스 체험,청소년,오프라인,수,25,2022-11-09
4,서울시청자미디어센터,찾아가는미디어나눔버스 체험,"김도경,이수현",2022-11-25,2022-11-25,찾아가는미디어나눔버스 체험,청소년,오프라인,금,25,2022-11-09
...,...,...,...,...,...,...,...,...,...,...,...
94,인천시청자미디어센터,찾아가는 미디어나눔버스(TV뉴스체험),"류은애,김은자",2022-11-30,2022-11-30,TV 뉴스 제작 및 영상합성 크로마키 체험,중학생,오프라인,수,25,2022-11-09
95,충북시청자미디어센터,TV체험(뉴스체험),미정,2022-11-01,2022-11-30,"아나운서, 기자, 기상캐스터 등 역할을 나누어 뉴스 제작 과정을 체험해보는 프로그램",초등학생 이상,오프라인,"월,화,수,목,금,토",15,2022-11-09
96,충북시청자미디어센터,라디오체험(DJ체험),미정,2022-11-01,2022-11-30,"라디오 프로그램을 작가, DJ, 게스트가 되어 라디오 프로그램을 제작해보는 체험",초등학생 이상,오프라인,"월,화,수,목,금,토",15,2022-11-09
97,충북시청자미디어센터,유아 크로마키 체험,미정,2022-11-01,2022-11-30,유아 대상 크로마키를 통해 다양한 놀이를 해보는 체험,6~7세,오프라인,"월,화,수,목,금,토",15,2022-11-09
98,충북시청자미디어센터,AI 체험,미정,2022-11-01,2022-11-30,인공지능에 대해 이해하고 머신러닝을 여러 방법으로 알아보는 체험,초등학생 이상,오프라인,"월,화,수,목,금,토",15,2022-11-09

In [34]:
df['강사명']=df['강사명'].apply(lambda x: '기타' if x=='미정' else x)

In [37]:
df['강사명']=df['강사명'].apply(lambda x: x.split('외') if '외' in x else x)

In [38]:
df['강사명']=df['강사명'].apply(lambda x: x.split('외') if '외' in x else x)df['강사명'].apply(lambda x: x.split(',') if ',' in x else x)

SyntaxError: invalid syntax (2020434795.py, line 1)